### ISSUE TITLE
Add php version to control your server from a browser.

### ISSUE THREAD

**Issue by TheJeterLP** [hide92795/RemoteController#4]
It would be nice, if you would make a PHP version of the app. I want to make a store with PHP, but I don't want to spam my server with plugins, who provide a remote API.

**Comment by hide92795** [comment]
I'm now creating web app version which running on various browsers. It is wrote with html and javascript. I don't think to create PHP version.

**Comment by TheJeterLP** [comment]
Why no PHP? I think it would be much more secure and easier to code ;)

**Comment by TheJeterLP** [comment]
Also if you need some help with PHP, I can help you. I'm a Java and PHP
developer.

**Comment by hide92795** [comment]
Because I am interested in creating web app with html/js.
I want to experience many other programming language, but I'm now fully occupied with another works :'(

**Comment by hide92795** [comment]
Thank you in advance for your cooperation :)
